# **Fitness_Classification**

# **Import Libraries**

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# **Read Dataset**

In [12]:
df = pd.read_csv("fitness_dataset.csv")

In [13]:
df.head()

,age,height_cm,weight_kg,heart_rate,blood_pressure,sleep_hours,nutrition_quality,activity_index,smokes,gender,is_fit
0,56,152,65,69.6,117.0,NaN,2.37,3.97,no,F,1
1,69,186,95,60.8,114.8,7.5,8.77,3.19,0,F,1
2,46,192,103,61.4,116.4,NaN,8.20,2.03,0,F,0
3,32,189,83,60.2,130.1,7.0,6.18,3.68,0,M,1
4,60,175,99,58.1,115.8,8.0,9.95,4.83,yes,F,1

# **Dataset Overview**

In [14]:
df.shape

(2000, 11)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                2000 non-null   int64
 1   height_cm          2000 non-null   int64
 2   weight_kg          2000 non-null   int64
 3   heart_rate         2000 non-null   float64
 4   blood_pressure     2000 non-null   float64
 5   sleep_hours        1840 non-null   float64
 6   nutrition_quality  2000 non-null   float64
 7   activity_index     2000 non-null   float64
 8   smokes             2000 non-null   object
 9   gender             2000 non-null   object
 10  is_fit             2000 non-null   int64
dtypes: float64(5), int64(4), object(2)
memory usage: 172.0+ KB

# **Statistical** **Analysis**

In [16]:
df.describe()

,age,height_cm,weight_kg,heart_rate,blood_pressure,sleep_hours,nutrition_quality,activity_index,is_fit
count,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,1840.000000,2000.000000,2000.000000,2000.000000
mean,49.114000,174.53300,83.540500,70.288600,119.908850,7.513315,5.035140,2.999040,0.399500
std,17.926564,14.37175,25.852534,11.846339,14.578032,1.502031,2.864156,1.136383,0.489918
min,18.000000,150.00000,30.000000,45.000000,90.000000,4.000000,0.000000,1.000000,0.000000
25%,34.000000,162.00000,64.000000,62.100000,109.700000,6.500000,2.547500,2.037500,0.000000
50%,49.000000,174.00000,83.000000,70.250000,120.000000,7.500000,5.065000,2.980000,0.000000
75%,65.000000,187.00000,102.000000,78.425000,129.800000,8.600000,7.470000,3.950000,1.000000
max,79.000000,199.00000,250.000000,118.600000,171.200000,12.000000,10.000000,4.990000,1.000000

# **Dataset** **Missign Values**

In [17]:
df.isnull().sum()

age                    0
height_cm              0
weight_kg              0
heart_rate             0
blood_pressure         0
sleep_hours          160
nutrition_quality      0
activity_index         0
smokes                 0
gender                 0
is_fit                 0
dtype: int64

In [18]:
df["sleep_hours"] = df["sleep_hours"].fillna(df["sleep_hours"].mean())

In [19]:
df.head()

,age,height_cm,weight_kg,heart_rate,blood_pressure,sleep_hours,nutrition_quality,activity_index,smokes,gender,is_fit
0,56,152,65,69.6,117.0,7.513315,2.37,3.97,no,F,1
1,69,186,95,60.8,114.8,7.500000,8.77,3.19,0,F,1
2,46,192,103,61.4,116.4,7.513315,8.20,2.03,0,F,0
3,32,189,83,60.2,130.1,7.000000,6.18,3.68,0,M,1
4,60,175,99,58.1,115.8,8.000000,9.95,4.83,yes,F,1

In [20]:
df['smokes'].value_counts()

smokes
yes    711
0      581
no     518
1      190
Name: count, dtype: int64

In [21]:
df['smokes'] = df['smokes'].replace({"yes":1, "no":0})

In [23]:
df['smokes'].value_counts()

smokes
1    711
0    581
0    518
1    190
Name: count, dtype: int64

In [24]:
df['gender'].value_counts()

gender
F    1030
M     970
Name: count, dtype: int64

In [25]:
df['gender'] =df['gender'].replace({'F':0,'M':1})

In [26]:
df["gender"].value_counts()

gender
0    1030
1     970
Name: count, dtype: int64

In [27]:
df.head()

,age,height_cm,weight_kg,heart_rate,blood_pressure,sleep_hours,nutrition_quality,activity_index,smokes,gender,is_fit
0,56,152,65,69.6,117.0,7.513315,2.37,3.97,0,0,1
1,69,186,95,60.8,114.8,7.500000,8.77,3.19,0,0,1
2,46,192,103,61.4,116.4,7.513315,8.20,2.03,0,0,0
3,32,189,83,60.2,130.1,7.000000,6.18,3.68,0,1,1
4,60,175,99,58.1,115.8,8.000000,9.95,4.83,1,0,1

In [28]:
df['is_fit'].value_counts()

is_fit
0    1201
1     799
Name: count, dtype: int64

In [29]:
x = df.drop("is_fit", axis=1)
y = df["is_fit"]

In [30]:
smote = SMOTE(random_state=42)
x_resampled, y_resampled = smote.fit_resample(x, y)

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x_resampled, y_resampled, test_size=0.2, random_state=42)

# **Feature Scaling**

In [32]:
scale = StandardScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)

# **Random Forest Model Building**

In [34]:
model = RandomForestClassifier()
model.fit(x_train, y_train)

# Predictions
y_pred = model.predict(x_test)
y_pred_proba = model.predict_proba(x_test)[:, 1]

# **Classification Report**

In [35]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

# ROC AUC requires probabilities or scores for the positive class
print("ROC AUC:", roc_auc_score(y_test, y_pred_proba))

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7941787941787942
Precision: 0.7842323651452282
Recall: 0.8008474576271186
F1 Score: 0.7924528301886793
ROC AUC: 0.867390176409547
Confusion Matrix:
 [[193  52]
 [ 47 189]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.79      0.80       245
           1       0.78      0.80      0.79       236

    accuracy                           0.79       481
   macro avg       0.79      0.79      0.79       481
weighted avg       0.79      0.79      0.79       481